project:
  type: website

website:
  title: "My_Memories"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/lakshmi-krishna-vr
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme: solar
    css: styles.css



