project:
  type: website
  output-dir: docs
website:
  title: "My_Memories"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/lakshmi-krishna-vr
      - icon: github
        href: https://github.com/Lakshmi-krishna-vr
format:
  html:
    theme: solar
    css: styles.css



